apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
{{- if .Values.expose.noneClusterIP }}
  clusterIP: None
{{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: jobservice
