apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.portal" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
{{- if .Values.expose.noneClusterIP }}
  clusterIP: None
{{- end }}
  ports:
    - port: {{ template "harbor.portal.servicePort" . }}
      targetPort: {{ template "harbor.portal.containerPort" . }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
