{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.clair" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
{{- if .Values.expose.noneClusterIP }}
  clusterIP: None
{{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: clair
{{ end }}
