{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.database" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
{{- if .Values.expose.noneClusterIP }}
  clusterIP: None
{{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: database
{{- end -}}